id: P006906
initial_creation_type: ocr
source_metadata:
  id: bdr:W25198
  title: འཚོལ།
  author: ''
  volumes:
    3192f2dddb6e426ab182bf2e44a81883:
      image_group_id: I1KG12360
      title: ''
      volume_number: 1
      total_pages: 195
      base_file: v001.txt
